package com.stanford.schoolbackend.core.auth;

public enum AuthEventType {
    LOGIN_SUCCESS, LOGIN_FAILURE, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,
    PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,
    ADMIN_PASSWORD_RESET, LOGOUT
}