--
-- Name: announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    content text NOT NULL,
    posted_at timestamp(6) with time zone,
    title character varying(255) NOT NULL,
    course_id bigint,
    teacher_id bigint,
    audience character varying(255),
    CONSTRAINT announcements_audience_check CHECK (((audience)::text = ANY ((ARRAY['ALL'::character varying, 'TEACHERS'::character varying, 'STUDENTS'::character varying])::text[])))
);


--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assignments (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    description text,
    due_date timestamp(6) with time zone,
    max_score integer,
    title character varying(255) NOT NULL,
    course_id bigint NOT NULL
);


--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_records (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    session_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT attendance_records_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying, 'EXCUSED'::character varying])::text[])))
);


--
-- Name: attendance_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_event_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_event_logs (
    id bigint NOT NULL,
    username_attempted character varying(255),
    user_id bigint,
    event_type character varying(50) NOT NULL,
    ip_address character varying(64),
    occurred_at timestamp without time zone NOT NULL
);


--
-- Name: auth_event_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auth_event_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auth_event_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auth_event_logs_id_seq OWNED BY public.auth_event_logs.id;


--
-- Name: book_copies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_copies (
    id bigint NOT NULL,
    copy_code character varying(255) NOT NULL,
    status character varying(255),
    book_id bigint NOT NULL,
    CONSTRAINT book_copies_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BORROWED'::character varying, 'LOST'::character varying, 'DAMAGED'::character varying])::text[])))
);


--
-- Name: book_copies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_copies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_copies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_loans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.book_loans (
    id bigint NOT NULL,
    borrowed_date date NOT NULL,
    due_date date NOT NULL,
    returned_date date,
    book_copy_id bigint NOT NULL,
    borrower_id bigint NOT NULL
);


--
-- Name: book_loans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.book_loans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_loans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255),
    isbn character varying(255),
    publisher character varying(255),
    title character varying(255) NOT NULL
);


--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_attendance_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_attendance_records (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    class_session_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT class_attendance_records_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying, 'EXCUSED'::character varying])::text[])))
);


--
-- Name: class_attendance_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class_attendance_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_attendance_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_sections (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    grade_level_id bigint NOT NULL,
    homeroom_teacher_id bigint
);


--
-- Name: class_sections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class_sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_sessions (
    id bigint NOT NULL,
    note character varying(255),
    session_date date NOT NULL,
    class_section_id bigint NOT NULL
);


--
-- Name: class_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    description text,
    title character varying(255) NOT NULL,
    teacher_id bigint NOT NULL
);


--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_metrics_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_metrics_snapshots (
    id bigint NOT NULL,
    active_classes integer NOT NULL,
    attendance_percentage double precision,
    snapshot_date date NOT NULL,
    total_students integer NOT NULL,
    total_teachers integer NOT NULL
);


--
-- Name: daily_metrics_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_metrics_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_metrics_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_verification_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false NOT NULL
);


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.email_verification_tokens_id_seq OWNED BY public.email_verification_tokens.id;


--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    enrolled_at timestamp(6) with time zone,
    status character varying(255),
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'DROPPED'::character varying])::text[])))
);


--
-- Name: enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_class_sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_class_sections (
    exam_id bigint NOT NULL,
    class_section_id bigint NOT NULL
);


--
-- Name: exam_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_subjects (
    exam_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


--
-- Name: exams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exams (
    id bigint NOT NULL,
    exam_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    term_id bigint NOT NULL
);


--
-- Name: exams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_invoice_line_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_invoice_line_items (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    fee_item_id bigint NOT NULL,
    invoice_id bigint NOT NULL
);


--
-- Name: fee_invoice_line_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_invoice_line_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_invoice_line_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_invoices (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    student_id bigint NOT NULL,
    term_id bigint NOT NULL
);


--
-- Name: fee_invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_items (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: fee_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    method character varying(255) NOT NULL,
    payment_date date NOT NULL,
    reference character varying(255),
    invoice_id bigint NOT NULL
);


--
-- Name: fee_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




--
-- Name: grade_levels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grade_levels (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    sort_order integer NOT NULL,
    stage character varying(255)
);


--
-- Name: grade_levels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grade_levels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_levels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marks (
    id bigint NOT NULL,
    max_score double precision,
    score double precision NOT NULL,
    exam_id bigint NOT NULL,
    student_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


--
-- Name: marks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    link character varying(255),
    message character varying(255) NOT NULL,
    read boolean NOT NULL,
    type character varying(255) NOT NULL,
    recipient_id bigint NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used boolean DEFAULT false NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    session_date date NOT NULL,
    topic character varying(255),
    course_id bigint NOT NULL
);


--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    parent_contact_number character varying(255),
    roll_number character varying(255),
    id bigint NOT NULL,
    class_section_id bigint,
    admission_number character varying(255)
);


--
-- Name: subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    code character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submissions (
    id bigint NOT NULL,
    feedback text,
    file_url character varying(255),
    grade integer,
    graded_at timestamp(6) with time zone,
    submitted_at timestamp(6) with time zone,
    text_content text,
    assignment_id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    department character varying(255),
    qualification character varying(255),
    id bigint NOT NULL
);


--
-- Name: terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terms (
    id bigint NOT NULL,
    end_date date,
    is_current boolean NOT NULL,
    name character varying(255) NOT NULL,
    start_date date,
    ending_soon_notified boolean DEFAULT false NOT NULL
);


--
-- Name: terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: username_sequences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.username_sequences (
    id bigint NOT NULL,
    sequence_key character varying(50) NOT NULL,
    last_value integer DEFAULT 0 NOT NULL
);


--
-- Name: username_sequences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.username_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: username_sequences_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.username_sequences_id_seq OWNED BY public.username_sequences.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    username character varying(255) NOT NULL,
    must_change_password boolean DEFAULT true NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    account_locked boolean DEFAULT false NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_event_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_event_logs ALTER COLUMN id SET DEFAULT nextval('public.auth_event_logs_id_seq'::regclass);


--
-- Name: email_verification_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens ALTER COLUMN id SET DEFAULT nextval('public.email_verification_tokens_id_seq'::regclass);


--
-- Name: password_reset_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);


--
-- Name: username_sequences id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.username_sequences ALTER COLUMN id SET DEFAULT nextval('public.username_sequences_id_seq'::regclass);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: attendance_records attendance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT attendance_records_pkey PRIMARY KEY (id);


--
-- Name: auth_event_logs auth_event_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_event_logs
    ADD CONSTRAINT auth_event_logs_pkey PRIMARY KEY (id);


--
-- Name: book_copies book_copies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT book_copies_pkey PRIMARY KEY (id);


--
-- Name: book_loans book_loans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_loans
    ADD CONSTRAINT book_loans_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: class_attendance_records class_attendance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance_records
    ADD CONSTRAINT class_attendance_records_pkey PRIMARY KEY (id);


--
-- Name: class_sections class_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sections
    ADD CONSTRAINT class_sections_pkey PRIMARY KEY (id);


--
-- Name: class_sessions class_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT class_sessions_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: daily_metrics_snapshots daily_metrics_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_metrics_snapshots
    ADD CONSTRAINT daily_metrics_snapshots_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_token_key UNIQUE (token);


--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);


--
-- Name: exam_class_sections exam_class_sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_class_sections
    ADD CONSTRAINT exam_class_sections_pkey PRIMARY KEY (exam_id, class_section_id);


--
-- Name: exam_subjects exam_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_subjects
    ADD CONSTRAINT exam_subjects_pkey PRIMARY KEY (exam_id, subject_id);


--
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);


--
-- Name: fee_invoice_line_items fee_invoice_line_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoice_line_items
    ADD CONSTRAINT fee_invoice_line_items_pkey PRIMARY KEY (id);


--
-- Name: fee_invoices fee_invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoices
    ADD CONSTRAINT fee_invoices_pkey PRIMARY KEY (id);


--
-- Name: fee_items fee_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_items
    ADD CONSTRAINT fee_items_pkey PRIMARY KEY (id);


--
-- Name: fee_payments fee_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fee_payments_pkey PRIMARY KEY (id);




--
-- Name: grade_levels grade_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_levels
    ADD CONSTRAINT grade_levels_pkey PRIMARY KEY (id);


--
-- Name: marks marks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT marks_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);


--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: terms terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);


--
-- Name: students uk4ijilwehsq4n3vhrdlq722lnc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk4ijilwehsq4n3vhrdlq722lnc UNIQUE (admission_number);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: class_attendance_records uk73yhumrwc5pnw8naat8e16edu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance_records
    ADD CONSTRAINT uk73yhumrwc5pnw8naat8e16edu UNIQUE (class_session_id, student_id);


--
-- Name: users uk_users_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_username UNIQUE (username);


--
-- Name: subjects ukaodt3utnw0lsov4k9ta88dbpr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT ukaodt3utnw0lsov4k9ta88dbpr UNIQUE (name);


--
-- Name: daily_metrics_snapshots ukc5la1t7qdeex92eu919v23bc5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_metrics_snapshots
    ADD CONSTRAINT ukc5la1t7qdeex92eu919v23bc5 UNIQUE (snapshot_date);


--
-- Name: marks ukd0yepfe9y3774aqxohv2k9neu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT ukd0yepfe9y3774aqxohv2k9neu UNIQUE (exam_id, subject_id, student_id);


--
-- Name: submissions ukeiqoen8c565i0gq79ritryilw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT ukeiqoen8c565i0gq79ritryilw UNIQUE (assignment_id, student_id);


--
-- Name: book_copies ukf2bi6ld4nn88uyra2kgxn6py2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT ukf2bi6ld4nn88uyra2kgxn6py2 UNIQUE (copy_code);


--
-- Name: enrollments uki0g6mfijtuh199nj653nva6j5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT uki0g6mfijtuh199nj653nva6j5 UNIQUE (student_id, course_id);


--
-- Name: attendance_records ukiy4tykyo7qt7i81isspplg4pd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT ukiy4tykyo7qt7i81isspplg4pd UNIQUE (session_id, student_id);


--
-- Name: fee_invoices ukjjb5bi7xdp89q8iuuc4ryx0ls; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoices
    ADD CONSTRAINT ukjjb5bi7xdp89q8iuuc4ryx0ls UNIQUE (student_id, term_id);


--
-- Name: books ukkibbepcitr0a3cpk3rfr7nihn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn);


--
-- Name: class_sessions ukmhhx6emh0q8y98l39lh43d4fs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT ukmhhx6emh0q8y98l39lh43d4fs UNIQUE (class_section_id, session_date);


--
-- Name: fee_items ukofvne616hqdbctydubtl913r7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_items
    ADD CONSTRAINT ukofvne616hqdbctydubtl913r7 UNIQUE (name);


--
-- Name: terms ukqdbo5nicw4lj82c8858ds6q76; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT ukqdbo5nicw4lj82c8858ds6q76 UNIQUE (name);


--
-- Name: grade_levels uktql7fiuaeq82do1lqgg4fi0iq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade_levels
    ADD CONSTRAINT uktql7fiuaeq82do1lqgg4fi0iq UNIQUE (name);


--
-- Name: username_sequences username_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.username_sequences
    ADD CONSTRAINT username_sequences_pkey PRIMARY KEY (id);


--
-- Name: username_sequences username_sequences_sequence_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.username_sequences
    ADD CONSTRAINT username_sequences_sequence_key_key UNIQUE (sequence_key);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);




--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: auth_event_logs auth_event_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_event_logs
    ADD CONSTRAINT auth_event_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: email_verification_tokens email_verification_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: class_sections fk35cmy5av9wgh1uyyn0kqoe35f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sections
    ADD CONSTRAINT fk35cmy5av9wgh1uyyn0kqoe35f FOREIGN KEY (homeroom_teacher_id) REFERENCES public.teachers(id);


--
-- Name: courses fk468oyt88pgk2a0cxrvxygadqg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk468oyt88pgk2a0cxrvxygadqg FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: exam_class_sections fk6lo6qoqqhr28f3lhbrv57nvto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_class_sections
    ADD CONSTRAINT fk6lo6qoqqhr28f3lhbrv57nvto FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id);


--
-- Name: marks fk6o5buy4g7i65v20hjy9inwn05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT fk6o5buy4g7i65v20hjy9inwn05 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: assignments fk6p1m72jobsvmrrn4bpj4168mg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fk6p1m72jobsvmrrn4bpj4168mg FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: students fk7xqmtv7r2eb5axni3jm0a80su; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk7xqmtv7r2eb5axni3jm0a80su FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: sessions fk88i8wngw96iw0fscc0t6uq422; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk88i8wngw96iw0fscc0t6uq422 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: enrollments fk8kf1u1857xgo56xbfmnif2c51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk8kf1u1857xgo56xbfmnif2c51 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: class_sections fkaku0sr7novuko4u12a4qsspow; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sections
    ADD CONSTRAINT fkaku0sr7novuko4u12a4qsspow FOREIGN KEY (grade_level_id) REFERENCES public.grade_levels(id);


--
-- Name: attendance_records fkb5ijilkgrgx66qn66iajdkyb9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT fkb5ijilkgrgx66qn66iajdkyb9 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: marks fkbobdu0dce8k5vpm5mbd5ggpb1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT fkbobdu0dce8k5vpm5mbd5ggpb1 FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: attendance_records fkcbo3envv2eea8f8sdfoqf188; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_records
    ADD CONSTRAINT fkcbo3envv2eea8f8sdfoqf188 FOREIGN KEY (session_id) REFERENCES public.sessions(id);


--
-- Name: announcements fkcbrf5570bepj9wk21ofsrpwp2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fkcbrf5570bepj9wk21ofsrpwp2 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: fee_invoices fkdgrlxjj3ghn7ufdf624hh8ch6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoices
    ADD CONSTRAINT fkdgrlxjj3ghn7ufdf624hh8ch6 FOREIGN KEY (term_id) REFERENCES public.terms(id);


--
-- Name: fee_payments fkefs5ft3gcnr9m1migvfttijki; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fkefs5ft3gcnr9m1migvfttijki FOREIGN KEY (invoice_id) REFERENCES public.fee_invoices(id);


--
-- Name: book_copies fkhlawea8y2e2dv0ta58vc6f5nr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_copies
    ADD CONSTRAINT fkhlawea8y2e2dv0ta58vc6f5nr FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- Name: enrollments fkho8mcicp4196ebpltdn9wl6co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkho8mcicp4196ebpltdn9wl6co FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: class_sessions fkhqmne25xbl6qjfajsbcjanonv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT fkhqmne25xbl6qjfajsbcjanonv FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id);


--
-- Name: submissions fkhwebuw14r6lb2ja85w9mwa8vf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkhwebuw14r6lb2ja85w9mwa8vf FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: exam_subjects fkjch8aoitlh00suy6iubnwkjr2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_subjects
    ADD CONSTRAINT fkjch8aoitlh00suy6iubnwkjr2 FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: class_attendance_records fkl5djyhsrdkxsqy11ocv8qwd86; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance_records
    ADD CONSTRAINT fkl5djyhsrdkxsqy11ocv8qwd86 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: fee_invoices fkliio7vfx4ubd04ydh1c6xn4ei; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoices
    ADD CONSTRAINT fkliio7vfx4ubd04ydh1c6xn4ei FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: book_loans fklrm13ag667d9pxyfhvunlxp98; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_loans
    ADD CONSTRAINT fklrm13ag667d9pxyfhvunlxp98 FOREIGN KEY (borrower_id) REFERENCES public.users(id);


--
-- Name: fee_invoice_line_items fkmd16og0lgvcw5are6w887maq3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoice_line_items
    ADD CONSTRAINT fkmd16og0lgvcw5are6w887maq3 FOREIGN KEY (fee_item_id) REFERENCES public.fee_items(id);


--
-- Name: exams fkmu0khqa81iq1bs2p1ty32a6iu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT fkmu0khqa81iq1bs2p1ty32a6iu FOREIGN KEY (term_id) REFERENCES public.terms(id);


--
-- Name: announcements fkmydovuy8nxi7ncs7dsu7tk1ik; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fkmydovuy8nxi7ncs7dsu7tk1ik FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: book_loans fkoyld3dbrnunaj75c7gy1w5qay; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.book_loans
    ADD CONSTRAINT fkoyld3dbrnunaj75c7gy1w5qay FOREIGN KEY (book_copy_id) REFERENCES public.book_copies(id);


--
-- Name: teachers fkpavufmal5lbtc60csriy8sx3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkpavufmal5lbtc60csriy8sx3 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: exam_subjects fkq5m35424eql3p01trdwkaxf2r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_subjects
    ADD CONSTRAINT fkq5m35424eql3p01trdwkaxf2r FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: notifications fkqqnsjxlwleyjbxlmm213jaj3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id) REFERENCES public.users(id);


--
-- Name: marks fkqsh7nyinh5ntyjr023na0qfaa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT fkqsh7nyinh5ntyjr023na0qfaa FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: fee_invoice_line_items fkr03r55gve0ex4vjkllli6j52g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_invoice_line_items
    ADD CONSTRAINT fkr03r55gve0ex4vjkllli6j52g FOREIGN KEY (invoice_id) REFERENCES public.fee_invoices(id);


--
-- Name: submissions fkrirbb44savy2g7nws0hoxs949; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkrirbb44savy2g7nws0hoxs949 FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: exam_class_sections fkrw2q06as9be6g4ktpk6iyy1bd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_class_sections
    ADD CONSTRAINT fkrw2q06as9be6g4ktpk6iyy1bd FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- Name: students fksi1sa580rjsyreh5f67si6kpl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fksi1sa580rjsyreh5f67si6kpl FOREIGN KEY (class_section_id) REFERENCES public.class_sections(id);


--
-- Name: class_attendance_records fktqy0a104jjv6hqtvwsjkneqxa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_attendance_records
    ADD CONSTRAINT fktqy0a104jjv6hqtvwsjkneqxa FOREIGN KEY (class_session_id) REFERENCES public.class_sessions(id);


--
-- Name: password_reset_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);



